index:
    path: /
    controller: App\Controller\Frontend\IndexController::index
    methods: [GET]

save:
    path: /back/buy/save
    controller: App\Controller\Backend\Buy\SaveController::index
    methods: [POST]

products:
    path: /back/activities
    controller: App\Controller\Backend\Activities\GetActivitiesController::index
    methods: [GET]
